apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
      annotations:
        timestamp: "{{timestamp}}"
    spec:
      containers:
      - name: user-management
        image: cristobalrios2001/user-management:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: DATABASE_PATH
          value: "./database/db.sqlite"
